### ISSUE TITLE
Error while trying to run the script

### ISSUE THREAD

**Issue by andrab777** [ciernialab/MicrogliaMorphology#3]
Hi! 
thank you for providing such an amazing pipeline! I am very eager to try it out!

Unfortunately, when I started the script in Fiji I got the following error message:

"Error:           Statement cannot begin with '<' in line 7:
      
            <<> ! DOCTYPE html >"

Do you have any clue or suggestion for me to overcome that issue? Highly appreciated!

Thank you in advance!

**Comment by jenn-kim** [comment]
Hello! Are you downloading and using this script?
https://github.com/ciernialab/MicrogliaMorphology/blob/main/macros-scripts/MicrogliaMorphology_Program.ijm

In your error, Fiji seems to be recognizing "<<> ! DOCTYPE html >" in line 7 of the script, which shouldn't be there since it's not an html document and also isn't present in the script. Could you please send a screenshot of the script that you downloaded/are running?

**Comment by andrab777** [comment]
Hi!
yes i followed the instructions and downloaded FracLac, BioVoxxel and your script. 
Please find attached a screenshot of my installation and a screenshot of me opening the script with Notepad.

Thank you for your help!

![screenshot](https://github.com/user-attachments/assets/d09508b7-c91d-4816-8f88-27e228de1346)
![screenshot2](https://github.com/user-attachments/assets/f49cd49d-45fa-486e-a911-06339f0d7036)

**Comment by andrab777** [comment]
ahhh I just realized that the mistake is somehow when i press "save as"......it just saves the link but not the actual code.
However, when i got to the code and manual press "download" it works.

I am sorry :D

**Comment by jenn-kim** [comment]
no worries, glad that got figured out!
